### ISSUE TITLE
Authorization Issue

### ISSUE THREAD

**Issue by ngopal** [alpacahq/example-hft#5]
Could be something silly, but I keep receiving an authorization issue when running tick_taker.py.

`
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/nats/aio/client.py", line 285, in connect
    yield from self._process_connect_init()
  File "/root/anaconda3/lib/python3.6/site-packages/nats/aio/client.py", line 1556, in _process_connect_init
    raise NatsError("nats: " + err_msg.rstrip('\r\n'))
nats.aio.errors.NatsError: nats: 'Authorization Violation'
`

I've tried entering my key and secret on both the commandline as arguments to the python script, and setting them as environment variables. The key and secret exactly match what I see in the web interface.

Any ideas?

**Comment by Petersoj** [comment]
Are you using the API keys for Live Trading or Paper Trading? This trading algorithm uses the Polygon streaming API which requires API keys generated for Live Trading. This is so the hft algorithm can stream data via NATS streaming through Polygon.

**Comment by anggarizkia** [comment]
> Could be something silly, but I keep receiving an authorization issue when running tick_taker.py.
> 
> `Traceback (most recent call last): File "/root/anaconda3/lib/python3.6/site-packages/nats/aio/client.py", line 285, in connect yield from self._process_connect_init() File "/root/anaconda3/lib/python3.6/site-packages/nats/aio/client.py", line 1556, in _process_connect_init raise NatsError("nats: " + err_msg.rstrip('\r\n')) nats.aio.errors.NatsError: nats: 'Authorization Violation'`
> 
> I've tried entering my key and secret on both the commandline as arguments to the python script, and setting them as environment variables. The key and secret exactly match what I see in the web interface.
> 
> Any ideas?

The error message you're encountering, "Authorization Violation," typically indicates that there is an issue with the authentication when trying to connect to a service that requires authorization, such as a message broker or API service.

Here are some common steps you can take to troubleshoot and resolve this issue:

Double-check your API key and secret: Ensure that you are using the correct API key and secret. Even a small typo or whitespace difference can lead to authentication failures.

Verify the service you are connecting to: Make sure you are trying to connect to the correct service and endpoint that corresponds to the API key and secret you have. Sometimes, services have different environments (e.g., sandbox, production), and you might be using the wrong one.

Check for environment variables: If you are setting your API key and secret as environment variables, make sure that the environment variables are correctly named and set before running your script. You can use echo $VARIABLE_NAME to verify that the environment variables contain the expected values.

Confirm API permissions: Ensure that the API key you are using has the necessary permissions to access the service you are connecting to. Some APIs require specific permissions or roles to perform certain actions.

Debugging the code: Review the code that initiates the connection to the service (in this case, the tick_taker.py script). Ensure that the code is correctly picking up the API key and secret and using them in the authentication process.

Rate limiting: Some APIs impose rate limits, so if you are making too many requests in a short period, it could result in authorization issues. Check if the service you are connecting to has any rate limits and make sure you are not exceeding them.

Network issues: Occasionally, authorization issues can be caused by network problems or firewalls that block outgoing requests. Ensure that your server or environment can reach the API service's endpoints.

If you've tried all these steps and are still facing authorization issues, it might be helpful to consult the documentation or support resources provided by the service you are trying to access. They may have specific troubleshooting steps or additional information about common issues with their API.

**Comment by anggarizkia** [comment]
> Are you using the API keys for Live Trading or Paper Trading? This trading algorithm uses the Polygon streaming API which requires API keys generated for Live Trading. This is so the hft algorithm can stream data via NATS streaming through Polygon.

If you are working with a trading algorithm that uses the Polygon streaming API and you're encountering issues with API keys, I recommend double-checking that you are using API keys specifically generated for live trading, as mentioned in your message. Make sure that these keys are correctly configured in your trading algorithm's code or configuration files. If you continue to experience issues, you may need to reach out to the support or documentation resources provided by Polygon or the platform you are using for assistance with your specific setup and configuration.
